services:
  - type: web
    name: educabot
    runtime: python

    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: python app.py

    envVars:
      - key: TOKEN
        sync: false

      - key: PORT
        value: "10000"

      - key: RENDER
        value: "true"